server:
  port: 8888
spring:
  application:
    name: configuration-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/QuocDang0704/microservices-config-server
          username:
          password:
          clone-on-start: true