server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://159.223.79.247:3306/quoc_order_service
    username: root
    password: quanla02@ciuz
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
