#spring:
#  data:
#    mongodb:
#      username: admin
#      password: 123
#      uri: mongodb://localhost:27017/product-service
spring:
  data:
    mongodb:
      uri: mongodb://admin:123@localhost:27017/?authSource=admin
      database: product-service
