server:
  port: 8183
management:
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  application:
    name: inventory-service
  datasource:
    url: jdbc:mysql://159.223.79.247:3306/quoc_order_service
    username: root
    password: quanla02@ciuz
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: 123
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://localhost:8180/auth/realms/microservices-realm

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
